import pathlib

MODULES_DIR = pathlib.Path(__file__).parent

# LLM Generation module.
LLM_GENERATION_MODEL_NAME = "google/flan-t5-small"

# Image Generation module.
IMAGE_GENERATION_MODEL_NAME = "dummy"

IMAGE_GENERATION_DIR = MODULES_DIR / "image_generation"
IMAGE_GENERATION_IMAGES_DIR = IMAGE_GENERATION_DIR / "images"

# RAG Retrieval module.
RAG_DIR = MODULES_DIR / "rag_retrieval"
RAG_DATA_DIR = RAG_DIR / "data"
RAG_CHUNKS_DIR = RAG_DATA_DIR / "chunks"
RAG_INDEX_DIR = RAG_DATA_DIR / "index"
RAG_DOCUMENTS_DIR = RAG_DATA_DIR / "raw_documents"

RAG_CONFIG_FILE = RAG_DIR / "rag_config.py"
RAG_CHUNKS_FILE = RAG_CHUNKS_DIR / "document_chunks.json"
RAG_INDEX_FILE = RAG_INDEX_DIR / "index.faiss"


RAG_EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


# Text Classification module.
TEXT_CLASSIFICATION_MODEL_NAME = "distilbert-base-uncased"

TEXT_CLASSIFICATION_DIR = MODULES_DIR / "text_classification"
TEXT_CLASSIFICATION_DATA_DIR = TEXT_CLASSIFICATION_DIR / "data"
TEXT_CLASSIFICATION_MODEL_CONFIGS_DIR = TEXT_CLASSIFICATION_DIR / "model_configs"
TEXT_CLASSIFICATION_MODEL_WEIGHTS_DIR = TEXT_CLASSIFICATION_DIR / "model_weights"
TEXT_CLASSIFICATION_TRAINING_PLOTS_DIR = TEXT_CLASSIFICATION_MODEL_WEIGHTS_DIR / "training_plots"

TEXT_CLASSIFICATION_RAW_DATA_FILE = TEXT_CLASSIFICATION_DATA_DIR / "queries.json"
TEXT_CLASSIFICATION_MODEL_CONFIG_FILE = TEXT_CLASSIFICATION_MODEL_CONFIGS_DIR / "config.json"
TEXT_CLASSIFICATION_MODEL_WEIGHTS_FILE = TEXT_CLASSIFICATION_MODEL_WEIGHTS_DIR / "best_model.pt"
TEXT_CLASSIFICATION_TRAINING_PLOTS_FILE = TEXT_CLASSIFICATION_TRAINING_PLOTS_DIR / "training_curves.png"
